// T-Shirt size specifications based on the provided size chart
// All measurements in inches
// Print area = Body dimensions minus 1 inch from all sides

export const TSHIRT_SIZES = {
  '2T': {
    label: '2T',
    bodyLength: 15.5,
    bodyWidth: 11,
    fullBodyLength: 15.5,
    sleeveLength: 9,
    maxPrintWidth: 7,
    maxPrintHeight: 8,
  },
  '3T': {
    label: '3T',
    bodyLength: 16.5,
    bodyWidth: 12,
    fullBodyLength: 16.5,
    sleeveLength: 9.5,
    maxPrintWidth: 7.5,
    maxPrintHeight: 9,
  },
  '4T': {
    label: '4T',
    bodyLength: 17.5,
    bodyWidth: 13,
    fullBodyLength: 17.5,
    sleeveLength: 10,
    maxPrintWidth: 8,
    maxPrintHeight: 9.5,
  },
  '5T': {
    label: '5T',
    bodyLength: 18.5,
    bodyWidth: 13.5,
    fullBodyLength: 18.5,
    sleeveLength: 10.5,
    maxPrintWidth: 8.5,
    maxPrintHeight: 10,
  },
  'YS': {
    label: 'YS',
    bodyLength: 22,
    bodyWidth: 14.5,
    fullBodyLength: 22,
    sleeveLength: 12,
    maxPrintWidth: 9,
    maxPrintHeight: 11,
  },
  'YM': {
    label: 'YM',
    bodyLength: 23.5,
    bodyWidth: 15.5,
    fullBodyLength: 23.5,
    sleeveLength: 13,
    maxPrintWidth: 9.5,
    maxPrintHeight: 12,
  },
  'YL': {
    label: 'YL',
    bodyLength: 25,
    bodyWidth: 16.5,
    fullBodyLength: 25,
    sleeveLength: 14,
    maxPrintWidth: 10,
    maxPrintHeight: 13,
  },
  'YXL': {
    label: 'YXL',
    bodyLength: 26.5,
    bodyWidth: 17.5,
    fullBodyLength: 26.5,
    sleeveLength: 15,
    maxPrintWidth: 11,
    maxPrintHeight: 14,
  },
  S: {
    label: 'S',
    bodyLength: 28,
    bodyWidth: 18,
    fullBodyLength: 28,
    sleeveLength: 15.875,
    // Maximum printable area for this size
    maxPrintWidth: 12,
    maxPrintHeight: 15,
  },
  M: {
    label: 'M',
    bodyLength: 29,
    bodyWidth: 20,
    fullBodyLength: 29,
    sleeveLength: 17,
    maxPrintWidth: 13,
    maxPrintHeight: 15.5,
  },
  L: {
    label: 'L',
    bodyLength: 30,
    bodyWidth: 22,
    fullBodyLength: 30,
    sleeveLength: 18.5,
    maxPrintWidth: 14,
    maxPrintHeight: 16,
  },
  XL: {
    label: 'XL',
    bodyLength: 31,
    bodyWidth: 24,
    fullBodyLength: 31,
    sleeveLength: 20,
    maxPrintWidth: 15,
    maxPrintHeight: 17,
  },
  '2XL': {
    label: '2XL',
    bodyLength: 32,
    bodyWidth: 26,
    fullBodyLength: 32,
    sleeveLength: 21.5,
    maxPrintWidth: 16,
    maxPrintHeight: 18,
  },
  '3XL': {
    label: '3XL',
    bodyLength: 33,
    bodyWidth: 28,
    fullBodyLength: 33,
    sleeveLength: 22.875,
    maxPrintWidth: 17,
    maxPrintHeight: 19,
  },
  '4XL': {
    label: '4XL',
    bodyLength: 34,
    bodyWidth: 30,
    fullBodyLength: 34,
    sleeveLength: 24.25,
    maxPrintWidth: 18,
    maxPrintHeight: 20,
  },
  '5XL': {
    label: '5XL',
    bodyLength: 35,
    bodyWidth: 32,
    fullBodyLength: 35,
    sleeveLength: 25.375,
    maxPrintWidth: 18,
    maxPrintHeight: 20,
  },
};

export const ARTWORK_SIZES = [
  { label: 'W 10.75"', width: 10.75, height: 0, lockBy: 'width' },
  { label: 'W 11"', width: 11, height: 0, lockBy: 'width' },
  { label: 'W 12"', width: 12, height: 0, lockBy: 'width' },
  { label: 'W 13"', width: 13, height: 0, lockBy: 'width' },
  { label: 'W 14"', width: 14, height: 0, lockBy: 'width' },
  { label: 'H 10.75"', width: 0, height: 10.75, lockBy: 'height' },
  { label: 'H 11"', width: 0, height: 11, lockBy: 'height' },
  { label: 'H 12"', width: 0, height: 12, lockBy: 'height' },
  { label: 'H 13"', width: 0, height: 13, lockBy: 'height' },
  { label: 'H 14"', width: 0, height: 14, lockBy: 'height' },
  { label: 'Custom', width: 0, height: 0, lockBy: 'none' },
];

export const TSHIRT_COLORS = [
  { name: 'Black', hex: '#000000' },
  { name: 'Navy', hex: '#1e3a5f' },
  { name: 'Dark Heather', hex: '#4a4a4a' },
  { name: 'Charcoal', hex: '#3d3d3d' },
  { name: 'Dark Grey', hex: '#5a5a5a' },
  { name: 'Forest Green', hex: '#2d5a3a' },
  { name: 'Royal Blue', hex: '#2563eb' },
  { name: 'Light Blue', hex: '#93c5fd' },
  { name: 'White', hex: '#ffffff' },
  { name: 'Sand', hex: '#d4c5a9' },
  { name: 'Maroon', hex: '#6b1d2e' },
  { name: 'Cardinal Red', hex: '#8b2232' },
  { name: 'Red', hex: '#dc2626' },
  { name: 'Orange', hex: '#ea580c' },
  { name: 'Pink', hex: '#ec4899' },
];

export const SIZE_ORDER = ['2T', '3T', '4T', '5T', 'YS', 'YM', 'YL', 'YXL', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'];
